// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

internal struct WriterResponse {
    var statusCode: Int {
        return httpResponse.statusCode
    }

    var contentType: String {
        return httpResponse.value(forHTTPHeaderField: "Content-Type") ?? "application/octet-stream"
    }

    let httpResponse: HTTPURLResponse
    let data: Data?
}
