// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.


import Foundation

extension Client: CoWriteAPI { 
    public func generateContent(request: Operations.GenerateContentRequest) async throws -> Operations.GenerateContentResponse {
        return try await makeRequest(
            configureRequest: { configuration in
                try configureGenerateContentRequest(with: configuration, request: request)
            },
            handleResponse: handleGenerateContentResponse
        )
    }
    public func listTemplates(request: Operations.ListTemplatesRequest) async throws -> Operations.ListTemplatesResponse {
        return try await makeRequest(
            configureRequest: { configuration in
                try configureListTemplatesRequest(with: configuration, request: request)
            },
            handleResponse: handleListTemplatesResponse
        )
    }
}

// MARK: - Request Configuration

private func configureGenerateContentRequest(with configuration: URLRequestConfiguration, request: Operations.GenerateContentRequest) throws {
    configuration.path = "/cowrite/organization/{organizationId}/team/{teamId}/generate"
    configuration.method = .post
    configuration.pathParameterSerializable = request
    configuration.contentType = "application/json"
    configuration.body = try jsonEncoder().encode(request.generateTemplateRequest)
    if configuration.body == nil {
        throw SerializationError.missingRequiredRequestBody
    }
    configuration.telemetryHeader = .userAgent
}

private func configureListTemplatesRequest(with configuration: URLRequestConfiguration, request: Operations.ListTemplatesRequest) throws {
    configuration.path = "/cowrite/organization/{organizationId}/team/{teamId}/template/{templateId}"
    configuration.method = .get
    configuration.pathParameterSerializable = request
    configuration.telemetryHeader = .userAgent
}

// MARK: - Response Handlers

private func handleGenerateContentResponse(response: WriterResponse) throws -> Operations.GenerateContentResponse {
    var responseObject = Operations.GenerateContentResponse(
        contentType: response.contentType,
        statusCode: response.statusCode,
        rawResponse: response.httpResponse
    )
    
    if responseObject.statusCode == 200 { 
        // res.headers = r.headers
        if response.contentType.matchContentType(pattern: "application/json"), let data = response.data {
            do {
                responseObject.draft = try JSONDecoder().decode(Shared.Draft.self, from: data)
            } catch {
                throw ResponseHandlerError.failedToDecodeJSON(error)
            }
        }
    } else if [400, 401, 403, 404, 500].contains(responseObject.statusCode) { 
        // res.headers = r.headers
        if response.contentType.matchContentType(pattern: "application/json"), let data = response.data {
            do {
                responseObject.failResponse = try JSONDecoder().decode(Shared.FailResponse.self, from: data)
            } catch {
                throw ResponseHandlerError.failedToDecodeJSON(error)
            }
        }
    }

    return responseObject
}

private func handleListTemplatesResponse(response: WriterResponse) throws -> Operations.ListTemplatesResponse {
    var responseObject = Operations.ListTemplatesResponse(
        contentType: response.contentType,
        statusCode: response.statusCode,
        rawResponse: response.httpResponse
    )
    
    if responseObject.statusCode == 200 { 
        // res.headers = r.headers
        if response.contentType.matchContentType(pattern: "application/json"), let data = response.data {
            do {
                responseObject.templateDetailsResponse = try JSONDecoder().decode(Shared.TemplateDetailsResponse.self, from: data)
            } catch {
                throw ResponseHandlerError.failedToDecodeJSON(error)
            }
        }
    } else if [400, 401, 403, 404, 500].contains(responseObject.statusCode) { 
        // res.headers = r.headers
        if response.contentType.matchContentType(pattern: "application/json"), let data = response.data {
            do {
                responseObject.failResponse = try JSONDecoder().decode(Shared.FailResponse.self, from: data)
            } catch {
                throw ResponseHandlerError.failedToDecodeJSON(error)
            }
        }
    }

    return responseObject
}

