// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.


import Foundation

extension Client: UserAPI { 
    public func listUsers(request: Operations.ListUsersRequest) async throws -> Operations.ListUsersResponse {
        return try await makeRequest(
            configureRequest: { configuration in
                try configureListUsersRequest(with: configuration, request: request)
            },
            handleResponse: handleListUsersResponse
        )
    }
}

// MARK: - Request Configuration

private func configureListUsersRequest(with configuration: URLRequestConfiguration, request: Operations.ListUsersRequest) throws {
    configuration.path = "/user"
    configuration.method = .get
    configuration.queryParameterSerializable = request
    configuration.telemetryHeader = .userAgent
}

// MARK: - Response Handlers

private func handleListUsersResponse(response: WriterResponse) throws -> Operations.ListUsersResponse {
    var responseObject = Operations.ListUsersResponse(
        contentType: response.contentType,
        statusCode: response.statusCode,
        rawResponse: response.httpResponse
    )
    
    if responseObject.statusCode == 200 { 
        // res.headers = r.headers
        if response.contentType.matchContentType(pattern: "application/json"), let data = response.data {
            do {
                responseObject.paginatedResultUserPublicResponse = try JSONDecoder().decode(Shared.PaginatedResultUserPublicResponse.self, from: data)
            } catch {
                throw ResponseHandlerError.failedToDecodeJSON(error)
            }
        }
    } else if [400, 401, 403, 404, 500].contains(responseObject.statusCode) { 
        // res.headers = r.headers
        if response.contentType.matchContentType(pattern: "application/json"), let data = response.data {
            do {
                responseObject.failResponse = try JSONDecoder().decode(Shared.FailResponse.self, from: data)
            } catch {
                throw ResponseHandlerError.failedToDecodeJSON(error)
            }
        }
    }

    return responseObject
}

