// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Client: WriterAPI {

    public var aiContentDetector: AIContentDetectorAPI {
        return self
    }
    public var billing: BillingAPI {
        return self
    }
    public var coWrite: CoWriteAPI {
        return self
    }
    public var completions: CompletionsAPI {
        return self
    }
    public var content: ContentAPI {
        return self
    }
    public var downloadTheCustomizedModel: DownloadTheCustomizedModelAPI {
        return self
    }
    public var files: FilesAPI {
        return self
    }
    public var modelCustomization: ModelCustomizationAPI {
        return self
    }
    public var models: ModelsAPI {
        return self
    }
    public var snippet: SnippetAPI {
        return self
    }
    public var styleguide: StyleguideAPI {
        return self
    }
    public var terminology: TerminologyAPI {
        return self
    }
    public var user: UserAPI {
        return self
    }
    public var document: DocumentAPI {
        return self
    }
}

// MARK: - Request Configuration

// MARK: - Response Handlers

