// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.


import Foundation

extension Operations.UpdateTermsRequest: Serializable {
    func serialize(with format: SerializableFormat) throws -> String {
        switch format {
        case .path:
            return try serializePathParameterSerializable(self, with: format)
        case .header:
            return serializeModel(with: try serializedHeaderParameters(), format: format)
        case .query, .multipart, .form:
            throw SerializationError.invalidSerializationParameter(type: "Operations.UpdateTermsRequest", format: format.formatDescription)
        }
    }
}

extension Operations.UpdateTermsRequest: PathParameterSerializable {
    func serializedPathParameters(formatOverride: SerializableFormat?) throws -> [String: String] {
        return [
            "organizationId": try organizationId?.serialize(with: formatOverride ?? .path(explode: false)),
            "teamId": try teamId.serialize(with: formatOverride ?? .path(explode: false)),
        ].compactMapValues { $0 }
    }
}

extension Operations.UpdateTermsRequest: HeaderParameterSerializable {
    func serializedHeaderParameters() throws -> [SerializedParameter] {
        return [
            SerializedParameter(name: "X-Request-ID", serialized: try xRequestID?.serialize(with: .header(explode: false)))
        ]
    }
}
